version: ~> 1.0

jdk:
  - openjdk8
import: land-of-apps/land-of-apps:travis/java-imports.yml

script:
  - ./gradlew test -x clustered:integration-test:test -x clustered:server:service-api:test -x clustered:server:service:test
