version: ~> 1.0

jdk:
  - openjdk8
import: land-of-apps/land-of-apps:travis/java-imports.yml

script:
  - travis_wait ./gradlew core:test --tests org.ehcache.core.collections.ConcurrentWeakIdentityHashMapTest --rerun-tasks
