include::common.adoc[]

= The Ehcache 3.x JSR-107 Provider

include::menu.adoc[]

== Getting started with Ehcache 3.0 & JSR-107

There is nothing special for you to do to use Ehcache 3.0 as the caching provider for your application: add the
`ehcache-3.0.0.jar` to your application's classpath (possibly removing the previous provider's jar) and you are ready to
go:

[source,java]
----
CachingProvider provider = Caching.getCachingProvider(); // <1>
CacheManager cacheManager = provider.getCacheManager(); // <2>
----
<1> Retrieves the default `CachingProvider`, this should be `org.ehcache.EhCachingProvider`.
    You can also force use of `org.ehcache.EhCachingProvider` by using the `Caching.getCachingProvider(String)` static method instead.
<2> Retrieve the default `CacheManager` instance using the provider.

== JSR-107 and Ehcache configuration integration

=== Starting from JSR-107 created caches

When you create a `Cache` on a `CacheManager` using a `MutableConfiguration` - that is you only use JSR-107 types -
you can still get to the underlying Ehcache `RuntimeCacheConfiguration`:

[source,java,indent=0]
----
include::../../107/src/test/java/org/ehcache/docs/EhCache107ConfigurationIntegrationDocTest.java[tag=mutableConfigurationExample]
----
<1> Create a JSR-107 cache using the `MutableConfiguration` from the specification
<2> Get to the JSR-107 `CompleteConfiguration`
<3> Get to the Ehcache JSR-107 configuration bridge
<4> Unwrap to the Ehcache `RuntimeCacheConfiguration` type

=== Building the configuration using Ehcache APIs

You can also create a JSR-107 `Cache` using an Ehcache `CacheConfiguration`.
When using this mechanism, no JSR-107 `CompleteConfiguration` is used and so you cannot get to one.

[source,java,indent=0]
----
include::../../107/src/test/java/org/ehcache/docs/EhCache107ConfigurationIntegrationDocTest.java[tag=ehcacheBasedConfigurationExample]
----
<1> Create an Ehcache `CacheConfiguration` - through a builder as shown here or even through XML
<2> Use the configuration with JSR-107 API by wrapping it
<3> Get back to the Ehcache `CacheConfiguration` ...
<4> or to the runtime configuration even.
<5> No JSR-107 `CompleteConfiguration` is available in this context

=== Getting JSR-107 caches configured through Ehcache XML

Another way to have the full Ehcache configuration options on your caches while having no code dependency on the provider is
to use XML based configuration. See link:xml{outfilesuffix}[the XML documentation] for more details on configuring `Cache`s in XML.

Find below the XML configuration followed by the code to use it from JSR-107:

[source,xml,indent=0]
----
include::../../107/src/test/resources/org/ehcache/docs/ehcache-jsr107-config.xml[]
----

[source,java,indent=0]
----
include::../../107/src/test/java/org/ehcache/docs/EhCache107ConfigurationIntegrationDocTest.java[tag=jsr107UsingXMLConfigExample]
----
<1> Invoking `javax.cache.spi.CachingProvider.getCacheManager(java.net.URI, java.lang.ClassLoader)`
<2> and passing in a URI that resolves to an Ehcache XLM configuration file.
<3> the second argument being the `ClassLoader` to use to load user-types if needed; i.e. `Class` instances that are
    stored in the `Cache` managed by our `CacheManager`.
<4> Get the configured `Cache` out of the `CacheManager`

NOTE: You can also use the `CachingProvider.getCacheManager()` method that takes no arguments instead.
      The `URI` and `ClassLoader` used to configure the `CacheManager` will then use the
      vendor specific values returned by `CachingProvider.getDefaultURI` and `.getDefaultClassLoader` respectively.
      Be aware that these are not entirely specified for Ehcache 3.0 and may change in future releases!

=== Supplement JSR-107's configurations

As of Ehcache 3.0, you can also create `cache-templates`.  See the
link:xml{outfilesuffix}#__code_cache_template_code_elements[Cache Templates] section of the XML Documentation for more details. The Ehcache 3.0
JSR-107 Caching Provider comes with an extension to the regular XML configuration so you can:

 . Configure a default template from which all programmatically created `Cache` instances inherit, and
 . Configure a given named `Cache` to inherit from a specific template.

This feature is particularly useful to configure `Cache` beyond the JSR-107 specification, for example, giving `Cache` a capacity
constraint. All that's needed is adding a `jsr107` service in your XML configuration file:

[source,xml,indent=0]
----
include::../../107/src/test/resources/org/ehcache/docs/ehcache-jsr107-template-override.xml[]
----
<1> First, declare a namespace for the 107 extension, e.g. `jsr107`
<2> Within a `service` element at the top of you configuration, add a `jsr107:defaults` element
<3> The element takes an optional attribute `default-template`, which references the `cache-template` to use for all
    `javax.cache.Cache` created by the application at runtime using `javax.cache.CacheManager.createCache`. In
    this example, the default `cache-template` used will be `tinyCache`, meaning that atop of their particular config,
    programmatically created `Cache` instances will have their capacity constrained to 20 entries.
<4> Nested within the `jsr107:defaults`, add specific `cache-templates` to use for given named `Cache`, e.g. when
    creating the `Cache` named `foos` at runtime, Ehcache will enhance its config, giving it a capacity of 2000 entries,
    as well as insuring both key and value types are `String`.

NOTE: See link:xsds{outfilesuffix}#_jsr_107_extension[this xsd] for complete definition

Using the above configuration, you can not only supplement but also override the configuration of JSR-107 created caches
without modifying the application code.

[source,java,indent=0]
----
include::../../107/src/test/java/org/ehcache/docs/EhCache107ConfigurationIntegrationDocTest.java[tag=jsr107SupplementWithTemplatesExample]
----
<1> Assume existing JSR-107 configuration code
<2> that creates JSR-107 `Cache`
<3> If you were to get to the Ehcache `RuntimeConfiguration`
<4> you could verify that the template configured capacity is applied to the cache and returns _20_ here.
<5> Templates will also override JSR-107 config, see here a configuration with TTL 1 minute
<6> used to create a cache where the template says TTL 2 minutes.
<7> And we can indeed verify that the template provided configuration has been applied, duration will be _2 minutes_ and not _1_.
<8> One drawback of this is that when getting at the `CompleteConfiguration`, you no longer have access to the factories from JSR-107.
