include::common.adoc[]

= The new Ehcache 3.x line

include::menu.adoc[]

== Getting started with the new API

NOTE: If you are looking to use the JSR-107, aka `javax.cache` API, you should start by reading
      link:107{outfilesuffix}[the Ehcache 3.x JSR-107 Provider page]

WARNING: *This is still a work in progress*. While it represents the API as it exists today, the final version will be represented in the Ehcache 3.0 OSS Beta.

=== Configuring it all in Java

==== Managed cache

[source,java,indent=0]
----
include::../../impl/src/test/java/org/ehcache/GettingStarted.java[tag=cachemanagerExample]
----

<1> Static method `org.ehcache.CacheManagerBuilder.newCacheManagerBuilder` that returns a new `org.ehcache.CacheManagerBuilder`
    instance;
<2> Use the builder to register a pre-configured `Cache` to be created when we `.build()` the actual `CacheManager`.
    The first `String` argument is the alias used to interact with the `Cache` through the `CacheManager`; the second
    argument is `org.ehcache.config.CacheConfiguration` to configure the `Cache`. We use the static
    `.newCacheConfigurationBuilder()` method on `org.ehcache.config.CacheConfigurationBuilder` to create a default config;
<3> Finally, invoking `.build()` returns a fully instantiated and initialized `CacheManager` we can use.
<4> We can retrieve the `preConfigured` aliased `Cache` we declared in step 2. For type-safety, we ask for both key and
    value types to be passed in. If these differ from the ones we expect, the `CacheManager` throws a `ClassCastException`
    early in the application's lifecycle. It also guards the `Cache` from being polluted by random types.
<5> The `CacheManager` can also be used to create new `Cache` as needed. Just as in step 2, it requires passing in an
    alias as well as a `CacheConfiguration`. The instantiated and fully initialized `Cache` added will be returned and/or
    accessed through the `CacheManager.getCache` API.
<6> We can now use the newly added `Cache` to store and ...
<7> ... retrieve data.
<8> We can also `CacheManager.remove()` a given `Cache`. The `CacheManager` will not only remove it's reference to the
    `Cache`, but will also close it. The `Cache` releases all locally held transient resources (such as memory).
    References to this `Cache` become unusable.
<9> In order to release all transient resources (memory, threads, ...) a `CacheManager` provides to `Cache` instances
     it manages, you have to invoke `CacheManager.close()`, which in turns closes all `Cache` instances known at the time.

==== Standalone cache

[source,java,indent=0]
----
include::../../impl/src/test/java/org/ehcache/GettingStarted.java[tag=standaloneCacheExample]
----

<1> A new feature of Ehcache 3.0 is the ability to create `StandaloneCache` instances, i.e. ones not managed by a `CacheManager`;
<2> As there is nothing that manages them, it is up to you to `StandaloneCache.init()` them, prior to using them.
<3> You can use the Standalone cache exactly as a managed cache
<4> In the same vein, a `StandaloneCache` requires you to `StandaloneCache.close()` it explicitly. If you would also use
    managed caches simultaneously, the `CacheManager.close()` operation would not impact the Standalone cache.

==== Off-heap

[source,java,indent=0]
----
include::../../impl/src/test/java/org/ehcache/GettingStarted.java[tag=offheapCacheManager]
----

<1> If you wish to use off-heap, you'll have to define resource pool, giving the memory size you want to allocate.

Do not forget to define in the java options the -XX:MaxDirectMemorySize option, according to the off-heap size you intend to use.

==== Disk persistence

[source,java,indent=0]
----
include::../../impl/src/test/java/org/ehcache/GettingStarted.java[tag=persistentCacheManager]
----

<1> If you wish to use disk storage (like for persistent `Cache` instances), you'll have to register a
    `LocalPersistenceService` with your `CacheManager`, which you can do by providing the location where
    data should be stored on disk to the `CacheManagerBuilder.persistence(String)` static method.
<2> You define a resource pool for the disk.

=== It wouldn't be Java without _some_ XML

You can create a XML file to configure a `CacheManager`:

[source,xml]
----
include::../../xml/src/test/resources/configs/getting-started.xml[tags=gettingStarted]
----

<1> Declares a `Cache` aliased to `foo`
<2> The keys of `foo` are declared as type `String`; since the value type is not specified, the values will be of type `Object`.
<3> `foo` is declared to hold up to 2,000 entries on heap...
<4> ...as well as up to 500 MB of off-heap memory before it starts evicting
<5> `<cache-template>` elements let you create an abstract configuration that further `<cache>` configuration can then _extend_
<6> `bar` is such a `Cache`.   `bar` uses the `<cache-template>` named `myDefaults` and overrides its `key-type` to a wider type.
<7> `simpleCache` is another such a `Cache`.  It uses `myDefaults` configuration for its sole `CacheConfiguration`.

Refer to the link:xml{outfilesuffix}[XML documentation] for more details on the XML format.

In order to parse an XML configuration, you can use the `XmlConfiguration` type:

[source,java]
----
final URL myUrl = this.getClass().getResource("/my-config.xml"); // <1>
Configuration xmlConfig = new XmlConfiguration(myUrl); // <2>
CacheManager myCacheManager = CacheManagerBuilder.newCacheManager(xmlConfig); // <3>
----

<1> Obtain a `URL` to your XML file's location
<2> Instantiate an `XmlConfiguration` passing the XML file's URL to it
<3> Using the static `org.ehcache.CacheManagerBuilder.newCacheManager(org.ehcache.config.Configuration)` lets you
    create your `CacheManager` instance using the `Configuration` from the `XmlConfiguration`

== Current release

We released the Milestone 1 on March 24, 2015. In addition to the JSR-107 compatibility,
it introduces tiering and offers an offheap option based on the recently https://github.com/Terracotta-OSS/offheap-store[open sourced library] from Terracotta.

The https://github.com/ehcache/ehcache3/releases/tag/v3.0.0.m1[release notes] contain the links to the documentation
to help you get started

== Current development & next release

We are now working on the next milestone, aka https://github.com/ehcache/ehcache3/milestones/OSS%20Beta[OSS Beta] :
All the features we want to port from the existing Ehcache 2.x line, exposed using the new API.
This includes things not covered by the JSR-107 spec, such as _WriteBehind_, _DiskPersistence_, _EvictionListener_ et al.

See the https://github.com/ehcache/ehcache3/milestones[Milestones on GitHub] for more details on the current status.

For developer information, you might want to go check the https://github.com/ehcache/ehcache3/wiki[Ehcache 3.0 project wiki on GitHub].
