---
---
ifndef::sourcedir[]
include::common.adoc[]
endif::sourcedir[]

= Ehcache 3.0 Documentation


ifdef::notBuildingForSite[]
include::menu.adoc[]
endif::notBuildingForSite[]

== Getting started with the new API

NOTE: If you are looking to use the JSR-107, aka `javax.cache` API, you should start by reading
      link:107{outfilesuffix}[the Ehcache 3.x JSR-107 Provider page]

WARNING: *This is still a work in progress*. While it represents the API as it exists today, the final version will be represented in the Ehcache 3.0 OSS Beta.

=== Configuring it all in Java

==== Managed cache

[source,java,indent=0]
----
include::{sourcedir}/impl/src/test/java/org/ehcache/docs/GettingStarted.java[tag=cachemanagerExample]
----

<1> Static method `org.ehcache.CacheManagerBuilder.newCacheManagerBuilder` that returns a new `org.ehcache.CacheManagerBuilder`
    instance;
<2> Use the builder to register a pre-configured `Cache` to be created when we `.build()` the actual `CacheManager`.
    The first `String` argument is the alias used to interact with the `Cache` through the `CacheManager`; the second
    argument is `org.ehcache.config.CacheConfiguration` to configure the `Cache`. We use the static
    `.newCacheConfigurationBuilder()` method on `org.ehcache.config.CacheConfigurationBuilder` to create a default config;
<3> Finally, invoking `.build(bool)` returns a fully instantiated, possibly initialized, `CacheManager` we can use;
<4> Before you start to use the `CacheManager` it needs to be `init()`, which can be done for you by the builder by passing `true` to `build(bool)`;
<5> We can retrieve the `preConfigured` aliased `Cache` we declared in step 2. For type-safety, we ask for both key and
    value types to be passed in. If these differ from the ones we expect, the `CacheManager` throws a `ClassCastException`
    early in the application's lifecycle. It also guards the `Cache` from being polluted by random types.
<6> The `CacheManager` can also be used to create new `Cache` as needed. Just as in step 2, it requires passing in an
    alias as well as a `CacheConfiguration`. The instantiated and fully initialized `Cache` added will be returned and/or
    accessed through the `CacheManager.getCache` API.
<7> We can now use the newly added `Cache` to store and ...
<8> ... retrieve data.
<9> We can also `CacheManager.remove()` a given `Cache`. The `CacheManager` will not only remove it's reference to the
    `Cache`, but will also close it. The `Cache` releases all locally held transient resources (such as memory).
    References to this `Cache` become unusable.
<10> In order to release all transient resources (memory, threads, ...) a `CacheManager` provides to `Cache` instances
     it manages, you have to invoke `CacheManager.close()`, which in turns closes all `Cache` instances known at the time.

==== User managed cache

[source,java,indent=0]
----
include::{sourcedir}/impl/src/test/java/org/ehcache/docs/UserManagedCaches.java[tag=userManagedCacheExample]
----

<1> A new feature of Ehcache 3.0 is the ability to create `UserManagedCache` instances, i.e. ones not managed by a `CacheManager`, again you can either have the builder `init()` it for you, passing true or
<2> pass false and it is up to you to `UserManagedCache.init()` them, prior to using them.
<3> You can use the cache exactly as a managed cache
<4> In the same vein, a `UserManagedCache` requires you to `UserManagedCache.close()` it explicitly. If you would also use
    managed caches simultaneously, the `CacheManager.close()` operation would not impact the user managed cache(s).

NOTE: See link:usermanaged{outfilesuffix}[the user managed cache documentation] for more information on this feature.

=== Tiering

==== Off-heap

[source,java,indent=0]
----
include::{sourcedir}/impl/src/test/java/org/ehcache/docs/GettingStarted.java[tag=offheapCacheManager]
----

<1> If you wish to use off-heap, you'll have to define resource pool, giving the memory size you want to allocate.

Do not forget to define in the java options the -XX:MaxDirectMemorySize option, according to the off-heap size you intend to use.

==== Disk persistence

[source,java,indent=0]
----
include::{sourcedir}/impl/src/test/java/org/ehcache/docs/GettingStarted.java[tag=persistentCacheManager]
----

<1> If you wish to use disk storage (like for persistent `Cache` instances), you'll have to register a
    `LocalPersistenceService` with your `CacheManager`, which you can do by providing the location where
    data should be stored on disk to the `CacheManagerBuilder.persistence(String)` static method.
<2> You define a resource pool for the disk.

==== Three tiers

[source,java,indent=0]
----
include::{sourcedir}/impl/src/test/java/org/ehcache/docs/GettingStarted.java[tag=threeTiersCacheManager]
----

<1> If you wish to use disk storage (like for persistent `Cache` instances), you'll have to register a
    `LocalPersistenceService` with your `CacheManager`, which you can do by providing the location where
    data should be stored on disk to the `CacheManagerBuilder.persistence(String)` static method.
<2> You define a resource pool for the heap.
<3> You define a resource pool for the off-heap.
<4> You define a resource pool for the disk.

==== Update ResourcePools

[source,java,indent=0]
----
include::{sourcedir}/impl/src/test/java/org/ehcache/docs/GettingStarted.java[tag=updateResourcesAtRuntime]
----

<1> You will need to create a new `ResourcePools` object with resources of required size, using `ResourcePoolsBuilder`. This object can
    then be passed to the said method so as to trigger the update.
<2> To update capacity of `ResourcePools`, `updateResourcePools(ResourcePools)` method in `RuntimeConfiguration` can be of help.
    `ResourcePools` object created earlier can then be passed to this method so as to trigger the update.

NOTE: Presently, `updateResourcePools()` only supports updating tiers that use `EntryUnit.ENTRIES` as the unit of measure.

=== Integration

==== Cache Event Listeners

[source,java,indent=0]
----
include::{sourcedir}/impl/src/test/java/org/ehcache/docs/GettingStarted.java[tag=cacheEventListener]
----

<1> Create a `CacheEventListenerConfiguration` using the builder indicating the listener class and the events to receive
<2> Optionally indicate the delivery mode - defaults are _asynchronous_ and _un-ordered_
<3> Pass the configuration of the listener into the cache configuration
<4> You will be notified on creation
<5> And on update
<6> But not on removal

Created, updated, and removed events are triggered by user execution of mutative methods as outlined in the table below.
Eviction and expiration events can be triggered by both internal processes and by user execution of methods targeting both related and unrelated keys within the cache.

.Cache entry event firing behaviors for mutative methods
[frame="topbot",cols="^1m,<4m,^1m,<4m",options="header"]
|=================================================================================================
| input   | operation                                | output  | event {key, old-value, new-value}
| {}      | put(K, V)                                | {K, V}  | created {K, null, V}
| {K, V1} | put(K, V2)                               | {K, V2} | updated {K, V1, V2}
| {}      | put(K, V) [immediately expired]          | {}      | none
| {K, V1} | put(K, V2) [immediately expired]         | {}      | none
|{}       | putIfAbsent(K, V)                        | {K, V}  | created {K, null, V}
|{}       | putIfAbsent(K, V) [immediately expired]  | {}      | none
|{K, V1}  | replace(K, V2)                           | {K, V2} | updated {K, V1, V2}
|{K, V1}  | replace(K, V2) [immediately expired]     | {}      | none
|{K, V1}  | replace(K, V1, V2)                       | {K, V2} | updated {K, V1, V2}
|{K, V1}  | replace(K, V1, V2) [immediately expired] | {}      | no events
|{K, V}   | remove(K)                                | {}      | removed {K, V, null}
|=================================================================================================

==== Write-Through Cache

[source,java,indent=0]
----
include::{sourcedir}/impl/src/test/java/org/ehcache/docs/GettingStarted.java[tag=writeThroughCache]
----

<1> If you wish to use a cache in read-through/write-through caching pattern, you'll have to implement
    `CacheLoaderWriter` and register `CacheLoaderWriterFactory` service by adding concrete type to the
    Cache using `DefaultCacheLoaderWriterConfiguration`.

==== Write-Behind Cache

[source,java,indent=0]
----
include::{sourcedir}/impl/src/test/java/org/ehcache/docs/GettingStarted.java[tag=writeBehindCache]
----

<1> A Cache can be used in write-behind pattern as well. You will have to implement `CacheLoaderWriter`
    and register using `DefaultCacheLoaderWriterConfiguration`.
<2> Additionally, register a `WriteBehindDecoratorLoaderWriterProvider` service to Cache by adding
    `WriteBehindConfiguration`.
<3> Enable write-behind queue to batch the updates to underlying resource.
<4> Configure maximum size of the writebehind queue.
<5> Define the concurrency level of writebehind queue, at a time these many writer threads will update
    the  underlying resource asynchronously.
<6> Enable the write coalescing behavior, which ensures that only latest update on a key hits the
    underlying resource.

=== Serializers

Serialization is primarily used in Ehcache to store the data in the non-heap tiers.
So whenever the user configures a multi-tiered cache, serialization and deserialization can happen when the data is moved to and from the tiers.
Ehcache provides default serializers that can serialize any `Serializable` type.
So if you are using standard `Serializable` types as your keys and values, no extra serializers need to be configured as the built-in serializer will handle those cases.
But if you use your own custom types in Ehcache that are not serializable, the stock serializer will not be able to perform the serialization/deserialization on its own.

==== Custom serializers

You can register your own custom serializers to the cache/cache manager.
So if you register a serializer for a given type of objects, it would be used to perform all the serialization/deserialization for that type.

You can configure serializers on the cache manager, to be applied to all caches:

[source,java,indent=0]
----
include::{sourcedir}/impl/src/test/java/org/ehcache/docs/GettingStarted.java[tag=defaultSerializers]
----

<1> Configure a global set of serializers. Each serializer is mapped to a type and the cache's declared key and value
    types are used to select the best serializer from the list. Each cache will pick a serializer for both key and value
    during initialization. If none is found, an error will be thrown. The serializer is chosen according to two rules:
    either there is one configured for the exact declared type, or the first type-compatible one from the list is chosen.
    By default, there is a serializer already configured for type `java.io.Serializable`.
<2> Don't forget to set the serializers' config on the `CacheManagerBuilder`.

Or you can configure specific serializers on the cache itself:

[source,java,indent=0]
----
include::{sourcedir}/impl/src/test/java/org/ehcache/docs/GettingStarted.java[tag=cacheSerializers]
----

<1> Configure the key's serializer.
<2> Configure the value's serializer.

Serializer instances are created per cache for keys and values separately.
That is, even if you configure the same serializer type for multiple caches, different instances are created for each cache.
The same applies to the serializers configured at the cache manager level as well.
Similarly, even within a cache, if you configure the same serializer type for both key and value, different instances are created. 

===== Implementation of a `Serializer`

When implementing a `org.ehcache.spi.serialization.Serializer`, you obviously need to respect the interface contract.

In addition, if you are using the `DefaultSerializationProvider` service provided by Ehcache; which would be the case
for most of the users, unless they are using their own implementation of `SerializationProvider` service; there are a
few implicit contracts:

* A serializer implementation to be used with transient caches must have a public constructor taking a `ClassLoader` as parameter.
* A serializer implementation to be used with persistent caches must have a public two-argument constructor taking a `ClassLoader` and a `FileBasedPersistenceContext` as parameters.
 
You are free to have as many extra constructors as you want. But these are the only constructors that will be used by
Ehcache to instantiate these serializers. For a transient cache the single-argument constructor will be used and for a
persistent cache the two-argument constructor will be used. Even though the user is enforced to have either or both the
constructors in his serializer implementation, the usage of these arguments is up to the user. The user can decide to
completely ignore these parameters. But the presence of these constructors is a strict requirement. Now, even though the
usage of the constructor arguments is not enforced, it is highly recommended to use the `FileBasedPersistenceContext` to
persist the state of the serializers, if there is any. 

==== Store-By-Value Caches with Copiers

JSR-107 mandates that the caches should support a store-by-value mechanism that makes a copy of the keys and values
before storing them in the cache. Ehcache supports store-by-reference by default on heap and the user needs to configure the
cache explicitly to use store-by-value.

The user can specify custom copy logic for keys and values to be used for copying.
The user can create a copier by implementing the `Copier<T>` interface directly if he has different needs for reads and writes.
Another option is to implement the helper class `ReadWriteCopier<T>` that has an abstract `copy(T obj)` method used by the `Copier<T>` methods.
If no copiers are provided, the cache will be a store-by-reference cache.

[source,java,indent=0]
----
include::{sourcedir}/impl/src/test/java/org/ehcache/docs/GettingStarted.java[tag=cacheCopiers]
----

<1> Configure the copier to be used for keys. *DescriptionCopier* in this case  as the keys are *Description* objects.
<2> Configure the copier to be used for values. *PersonCopier* in this case as the values are *Person* objects.

Now, if the user does not want to create his own custom copiers and still wants to have a store-by-value cache, ehcache
provides a `SerializingCopier` that the user can directly use. `SerializingCopier` internally uses serialization to
perform the copying. For serialization the serializers configured for the keys/values are used. You can configure the
cache as follows to use serializing copier:

[source,java,indent=0]
----
include::{sourcedir}/impl/src/test/java/org/ehcache/docs/GettingStarted.java[tag=cacheSerializingCopiers]
----

<1> Provide the `SerializingCopier` just like any other custom copier in the copier configuration and that is all you
    have to do. It is that simple.

If you look at the cache configuration in the above example, there are no copiers configured for the keys, and that is
fine in Ehcache. If a copier is not configured, we fall back to store-by-reference. So with the above configuration, you
get a cache that stores keys _by-reference_ and values _by-value_.

You can also have default copiers configured at the cache manager level so that you don't have to configure the same
copiers again and again for multiple caches managed by the same cache manager. This is how you can do that:

[source,java,indent=0]
----
include::{sourcedir}/impl/src/test/java/org/ehcache/docs/GettingStarted.java[tag=defaultCopiers]
----

<1> Create a `DefaultCopyProviderConfiguration` and add all the required default copiers.
<2> Use the same configuration in the `CacheManagerBuilder`.
<3> The `DescriptionCopier` and `PersonCopier` configured at the cache manager level will be used for this cache.
<4> The `PersonCopier` configured at the cache manager level will be used for this cache.

The samples above demonstrated the configuration of different services at the cache and the cache manager levels.
In none of the samples did we really create instances of copiers, serializers etc.
Instead we supplied the class types with the service configurations and the instantiation was done internally by Ehcache.
Even though that is the recommended way of configuring services, it is still possible to configure a service with actual
instances.

The following sample demonstrates the same for copier service. Other services can also be configured in a similar way:

[source,java,indent=0]
----
include::{sourcedir}/impl/src/test/java/org/ehcache/docs/GettingStarted.java[tag=cacheServiceConfigurations]
----

<1> Configuring the `DescriptionCopier` copier using class type(the old way). 
<2> Configuring the copier using an actual instance: The `PersonCopier` instance here.

WARNING: The former way of configuring services using class types is still the recommended way as that ensures that
the service instances are not shared between caches. Sharing services can have disastrous effects in your application if
the user is not careful enough. The latter way of configuring services using instances opens the door for sharing the
same service instance across caches but that feature should be used with extra care.

NOTE: By now you are familiar with configuring different services using actual instances or using class types of
loader-writers, serializers etc. It is desirable to have some cleanup performed on these instances once you are done
using the cache that uses these instances. You can achieve this by making your custom class types `Closeable` and
keeping your resource release logic in the _close_ method. Ehcache will make sure that this _close_ will be invoked when
the cache is removed from the cache manager or when the cache manager is closed. 

=== It wouldn't be Java without _some_ XML

You can create a XML file to configure a `CacheManager`:

[source,xml]
----
include::{sourcedir}/xml/src/test/resources/configs/getting-started.xml[tags=gettingStarted]
----

<1> Declares a `Cache` aliased to `foo`
<2> The keys of `foo` are declared as type `String`; since the value type is not specified, the values will be of type `Object`.
<3> `foo` is declared to hold up to 2,000 entries on heap...
<4> ...as well as up to 500 MB of off-heap memory before it starts evicting
<5> `<cache-template>` elements let you create an abstract configuration that further `<cache>` configuration can then _extend_
<6> `bar` is such a `Cache`.   `bar` uses the `<cache-template>` named `myDefaults` and overrides its `key-type` to a wider type.
<7> `simpleCache` is another such a `Cache`.  It uses `myDefaults` configuration for its sole `CacheConfiguration`.

Refer to the link:xml{outfilesuffix}[XML documentation] for more details on the XML format.

In order to parse an XML configuration, you can use the `XmlConfiguration` type:

[source,java]
----
final URL myUrl = this.getClass().getResource("/my-config.xml"); // <1>
Configuration xmlConfig = new XmlConfiguration(myUrl); // <2>
CacheManager myCacheManager = CacheManagerBuilder.newCacheManager(xmlConfig); // <3>
----

<1> Obtain a `URL` to your XML file's location
<2> Instantiate an `XmlConfiguration` passing the XML file's URL to it
<3> Using the static `org.ehcache.CacheManagerBuilder.newCacheManager(org.ehcache.config.Configuration)` lets you
    create your `CacheManager` instance using the `Configuration` from the `XmlConfiguration`

== Current development

For developer information, you might want to go check the https://github.com/ehcache/ehcache3/wiki[Ehcache 3.0 project wiki on GitHub].
