---
---
= User managed caches
ifndef::sourcedir31[]
include::common.adoc[]
endif::sourcedir31[]

ifdef::notBuildingForSite[]
include::menu.adoc[]
endif::notBuildingForSite[]

== What are user managed caches and what do they offer?

User managed caches is a new concept introduced in Ehcache 3.
It offers the ability to create caches that are not managed by a `CacheManager`.
Hence the name of _user managed_ caches.

The objective of this feature is to satisfy cache use cases where the added complexity of a cache manager is of no added value.
Ideas are: method local caches, thread local caches or any other place where the lifecycle of the cache is shorter than the application lifecycle.

=== Limitations

As there is no longer a cache manager offering up services, the main limitation of user managed caches is that the user has to configure all required services by hand.
Of course, if you find yourself requiring plenty of services, maybe the cache manager is a better option!

=== API extensions

If you use a `UserManagedCache`, you need to configure all required services by hand.
The `UserManagedCache` class extends the `Cache` class by offering additional methods:

* `init()` - initializes the cache
* `close()` - releases the cache resources
* `getStatus()` - returns a status

The `init` and `close` methods deal with the lifecycle of the cache and need to be called explicitly, whereas these methods are hidden when the cache is inside a `CacheManager`.

The interface definition is shown in this code:

[source,java,indent=0]
----
include::{sourcedir31}/api/src/main/java/org/ehcache/UserManagedCache.java[lines=17..-1]
----

=== User Managed Persistent Cache

A user managed persistent cache holds cached data in a persistent store such as disk, so that the stored data can outlive the JVM in which your caching application runs.
If you want to create a user managed persistent cache, there is an additional interface `PersistentUserManagedCache` that extends `UserManagedCache` and adds the `destroy` method.
The `destroy` method deletes all data structures, including data stored persistently on disk, for a `PersistentUserManagedCache`.
The `destroy` method deals with the lifecycle of the cache and needs to be called explicitly.

The interface definition is shown in this code:

[source,java,indent=0]
----
include::{sourcedir31}/api/src/main/java/org/ehcache/PersistentUserManagedCache.java[lines=17..-1]
----


== Code examples for User Managed Caches

=== Example of a basic cache lifecycle

Here is a simple example showing a basic lifecycle of a user managed cache:

[source,java,indent=0]
----
include::{sourcedir31}/impl/src/test/java/org/ehcache/docs/UserManagedCaches.java[tag=userManagedCacheExample]
----
<1> Create a `UserManagedCache` instance. You can either pass "true" to have the builder `init()` it for you, or you can pass "false" and it is up to you to `init()` it prior to using it.
<2> Since "false" was passed in step 1, you have to `init()` the `UserManagedCache` prior to using it.
<3> You can use the cache exactly as a managed cache
<4> In the same vein, a `UserManagedCache` requires you to close it explicitly using `UserManagedCache.close()`. 
If you are also using managed caches simultaneously, the `CacheManager.close()` operation does not impact the user managed cache(s).

From this basic example, explore the API of `UserManagedCacheBuilder` to find all the directly available features.

The following features apply in the exact same way to user managed caches:

* <<serializers-copiers.adoc#,Serializers and copiers>>
* <<eviction-advisor.adoc#,Eviction advisor>>

Simply use the methods from `UserManagedCacheBuilder` which are equivalent to the ones from `CacheConfigurationBuilder`.

Below we will describe some more advanced setup where there is a need to maintain a service instance in order to have a working user managed cache.

=== Example with disk persistence and lifecycle

If you want to use a disk persistent cache, you will need to create and lifecycle the persistence service.

[source,java,indent=0]
----
include::{sourcedir31}/impl/src/test/java/org/ehcache/docs/UserManagedCaches.java[tag=persistentUserManagedCache]
----
<1> Create the persistence service to be used by the cache for storing data on disk
<2> Pass the persistence service to the builder as well as a name for the cache. Note that this will make the builder produce a more specific type: `PersistentUserManagedCache`
<3> As usual, indicate here if the data should outlive the cache
<4> Closing the cache will not delete the data it saved on disk, since the cache is marked as persistent.
<5> To delete the data on disk after closing the cache, you need to invoke the `destroy` method explicitly.
<6> You need to stop the persistence service once you have finished using the cache.

=== Example with cache event listeners

Cache event listeners require executor services to work.
You will have to provide either a `CacheEventDispatcher` implementation
or make use of the default one by providing two executor services: one for ordered events and one for unordered ones.

NOTE: The ordered events executor must be single threaded to guarantee ordering.

For more information on cache event listeners, see <<cache-event-listeners.adoc#,the section dedicated to them>>.

[source,java,indent=0]
----
include::{sourcedir31}/impl/src/test/java/org/ehcache/docs/UserManagedCaches.java[tag=userManagedListenerCache]
----
<1> Provide the `ExecutorService` for ordered and unordered event delivery.
<2> Provide listener configuration using `CacheEventListenerConfigurationBuilder`.
