include::common.adoc[]

== Getting started with Ehcache 3.0 & XA transactional caches

Ehcache 3.0 supports caches that work within a XA transaction's context controlled by a JTA transaction manager, fully
supporting the whole two-phase commit protocol, including crash recovery.

=== What is supported and what are the limitations

 * Bitronix TM 2.1.4 is the only supported JTA implementation. Other JTA implementations may work but have not yet been
   tested.
 * Read-Committed is the only supported isolation level.
 * The isolation level is guaranteed by the use of the `Copier` mechanism. When no copiers are configured for either the
   key or the value, default ones are automatically used instead. You cannot disable the `Copier` mechanism for a
   transactional cache.
 * Configured cache eviction veto policies are ignored.
 * Configured cache eviction prioritization policies are ignored.
 * Accessing a cache access outside of a JTA transaction context is forbidden.
 * There is no protection against the ABA problem.
 * Everything else works orthogonally.

=== Configuring it all in Java

==== The simplest case

The simplest possible configuration is to configure a cache as XA-transactional and let Ehcache 3 figure out everything
else, meaning it will auto-detect and integrate with the Bitronix transaction manager.

This `INFO` log informs you of the detected transaction manager:

[source]
----
INFO o.e.t.x.c.DefaultTransactionManagerProvider - Using looked up transaction manager : a BitronixTransactionManager with 0 in-flight transaction(s)
----

[source,java,indent=0]
----
include::{sourcedir}/transactions/src/test/java/org/ehcache/transactions/xa/docs/XAGettingStarted.java[tag=testSimpleXACache]
----

<1> First start the Bitronix transaction manager. By default, Ehcache 3 will auto-detect it but will throw an exception
    during the cache manager initialization if BTM isn't started.
<2> Register a cache the normal way.
<3> Give it the resources you wish.
<4> Add a `XAStoreConfiguration` object to make the cache XA transactional. You must also give the cache a unique
    XAResource identifier as some transaction managers require this.
<5> Begin a JTA transaction the normal way.
<6> Work with the cache the normal way, all operations are supported. Note that concurrent transactions will not see
    those pending changes.
<7> Commit the JTA transaction. Other transactions can now see the changes you made to the cache.

==== Configuring your transaction manager

While only the Bitronix JTA implementation has been tested so far, plugging-in another one is possible.

This `INFO` log informs you about what transaction manager has been configured:

[source]
----
INFO o.e.t.x.c.DefaultTransactionManagerProvider - Using configured transaction manager : a BitronixTransactionManager with 0 in-flight transaction(s)
----

[source,java,indent=0]
----
include::{sourcedir}/transactions/src/test/java/org/ehcache/transactions/xa/docs/XAGettingStarted.java[tag=testXACacheWithSpecificJtaTm]
----

<1> First start the Bitronix transaction manager. By default, Ehcache 3 will auto-detect it but will throw an exception
    during the cache manager initialization if BTM isn't started.
<2> Register a cache the normal way.
<3> Give it the resources you wish.
<4> Add a `XAStoreConfiguration` object to make the cache XA transactional. You must also give the cache a unique
    XAResource identifier as some transaction managers require this.
<5> A `TransactionManagerProviderConfiguration` containing a `TransactionManagerWrapper` instance must be added to the
    builder. The `TransactionManagerWrapper` class is constructed with both the `javax.transaction.TransactionManager`
    instance as well as a `XAResourceRegistry` instance. The latter is used to register the
    `javax.transaction.xa.XAResource` instances of the cache with the transaction manager using an
    implementation-specific mechanism. If your JTA implementation doesn't require that, you can use the
    `NullXAResourceRegistry` instead.
<6> Begin a JTA transaction the normal way.
<7> Work with the cache the normal way, all operations are supported. Note that concurrent transactions will not see
    those pending changes.
<8> Commit the JTA transaction. Other transactions can now see the changes you made to the cache.

==== XA write-through cache

When a XA cache is configured in write-though mode, the targeted SoR will automatically participate in the JTA
transaction context. Nothing special needs to be configured for this to happen, just ensure that the configured
`CacheLoaderWriter` is configured to work with XA transactions.

[source,java,indent=0]
----
include::{sourcedir}/transactions/src/test/java/org/ehcache/transactions/xa/docs/XAGettingStarted.java[tag=testXACacheWithWriteThrough]
----

<1> First start the Bitronix transaction manager. By default, Ehcache 3 will auto-detect it but will throw an exception
    during the cache manager initialization if BTM isn't started.
<2> Register a cache the normal way.
<3> Give it the resources you wish.
<4> Add a `XAStoreConfiguration` object to make the cache XA transactional. You must also give the cache a unique
    XAResource identifier as some transaction managers require this.
<5> configure the `CacheLoaderWriter` here. this is a mocked SoR backed by a map for illustration that contains 1/"eins"
    key/value pair at startup.
<6> Begin a JTA transaction the normal way.
<7> The cache is empty at startup, so the `CacheLoaderWriter` will be called to load the value.
<8> Update the value. This will make the `CacheLoaderWriter` write to the SoR.
<9> Commit the JTA transaction. Other transactions can now see the changes you made to the cache and the SoR.

==== XA cache with three tiers and persistence

When a cache is configured as persistent, the in-doubt transactions are preserved and can be recovered across restarts.

This `INFO` log informs you about that in-doubt transactions journaling is persistent too:

[source]
----
INFO o.e.t.x.j.DefaultJournalProvider - Using persistent XAStore journal
----

[source,java,indent=0]
----
include::{sourcedir}/transactions/src/test/java/org/ehcache/transactions/xa/docs/XAGettingStarted.java[tag=testXACacheWithThreeTiers]
----

<1> First start the Bitronix transaction manager. By default, Ehcache 3 will auto-detect it but will throw an exception
    during the cache manager initialization if BTM isn't started.
<2> Register a cache the normal way.
<3> Give it the resources you wish.
<4> Add a `XAStoreConfiguration` object to make the cache XA transactional. You must also give the cache a unique
    XAResource identifier as some transaction managers require this.
<5> configure the `CacheLoaderWriter` here. this is a mocked SoR backed by a map for illustration that contains `1L`/`"eins"`
    key/value pair at startup.
<6> Begin a JTA transaction the normal way.
<7> The cache is empty at startup, so the `CacheLoaderWriter` will be called to load the value.
<8> Update the value. This will make the `CacheLoaderWriter` write to the SoR.
<9> Commit the JTA transaction. Other transactions can now see the changes you made to the cache and the SoR.


=== Configuring it with XML

You can create a XML file to configure a `CacheManager`, lookup a specific transaction manager and configure
XA caches:

[source,xml]
----
include::{sourcedir}/transactions/src/test/resources/docs/configs/xa-getting-started.xml[tags=gettingStarted]
----

<1> Declare a `TransactionManagerProvider` that will lookup your transaction manager.
<2> Configure a `xaCache` cache the normal way.
<3> Configure `xaCache` as an XA cache, giving it `xaCache` as its unique XAResource ID.

In order to parse an XML configuration, you can use the `XmlConfiguration` type:

[source,java]
----
include::{sourcedir}/transactions/src/test/java/org/ehcache/transactions/xa/docs/XAGettingStarted.java[tag=testXACacheWithXMLConfig]
----

<1> The Bitronix transaction manager must be started before the cache manager is initialized.
<2> Create a `URL` to your XML file's location.
<3> Instantiate a `XmlConfiguration` passing it the XML file's `URL`.
<4> Using the static `org.ehcache.CacheManagerBuilder.newCacheManager(org.ehcache.config.Configuration)` lets you
    create your `CacheManager` instance using the `Configuration` from the `XmlConfiguration`.

And here is what the `TransactionManagerProvider` implementation looks like:

[source,java]
----
include::{sourcedir}/transactions/src/test/java/com/pany/BitronixProvider.java[tag=BitronixProvider]
----

<1> The `TransactionManagerProvider` interface must be implemented.
<2> The `getTransactionManagerWrapper()` method must return a `TransactionManagerWrapper` instance.
<3> Here is the check that makes sure BTM is started. This isn't required and BTM could be configured and started
    in the `start()` method and shut down in the `stop()` method for instance, depending on your own requirements.
<4> The `TransactionManagerWrapper` class is constructed with both the `javax.transaction.TransactionManager`
    instance as well as a `XAResourceRegistry` instance. The latter is used to register the
    `javax.transaction.xa.XAResource` instances of the cache with the transaction manager using an
    implementation-specific mechanism. If your JTA implementation doesn't require that, you can use the
    `NullXAResourceRegistry` instead.
